# Generated by Django 4.2.3 on 2023-07-28 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import web.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_number', models.CharField(max_length=64, unique=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
                ('denotation', models.CharField(max_length=1024)),
                ('description', models.CharField(blank=True, max_length=65536, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denotation', models.CharField(max_length=4096)),
                ('description', models.CharField(blank=True, max_length=65536, null=True)),
            ],
            options={
                'ordering': ['denotation'],
            },
            bases=(web.models.base.DefaultToStringMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('diverse', 'Diverse'), ('unknown', 'Unknown')], max_length=9)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('institution_free', models.CharField(blank=True, max_length=512, null=True)),
                ('last_name', models.CharField(max_length=512)),
                ('first_name', models.CharField(blank=True, max_length=512, null=True)),
                ('division', models.CharField(blank=True, max_length=512, null=True)),
                ('role', models.CharField(blank=True, max_length=512, null=True)),
                ('comments', models.CharField(blank=True, max_length=65536, null=True)),
                ('institution_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.client')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denotation', models.CharField(max_length=4096)),
                ('description', models.CharField(blank=True, max_length=65536, null=True)),
            ],
            options={
                'ordering': ['denotation'],
            },
            bases=(web.models.base.DefaultToStringMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExhibitComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denotation', models.CharField(max_length=4096)),
                ('short', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['denotation'],
                'abstract': False,
            },
            bases=(web.models.base.DefaultToStringMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExhibitDataImageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denotation', models.CharField(max_length=4096)),
                ('short', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['denotation'],
                'abstract': False,
            },
            bases=(web.models.base.DefaultToStringMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExhibitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denotation', models.CharField(max_length=4096)),
                ('short', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['denotation'],
                'abstract': False,
            },
            bases=(web.models.base.DefaultToStringMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
                ('mandate_number', models.CharField(max_length=64, unique=True)),
                ('denotation', models.CharField(blank=True, max_length=4096, null=True)),
                ('date_mandate_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(blank=True, max_length=65536, null=True)),
                ('comments', models.CharField(blank=True, max_length=65536, null=True)),
                ('priority', models.CharField(default='', max_length=4096)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.client')),
                ('client_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.contactperson')),
                ('investigation_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='investigation_group_set', to='web.client')),
                ('investigation_group_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='investigation_group_contact_set', to='web.contactperson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='client_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.clientcategory'),
        ),
    ]
