# Generated by Django 4.2.3 on 2023-07-28 17:35

from django.db import migrations, models
import django.db.models.deletion
import web.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_client_clientcategory_contactperson_crimecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denotation', models.CharField(max_length=4096)),
                ('serial_number', models.CharField(blank=True, max_length=128, null=True)),
                ('handover_certificate_position_number', models.CharField(blank=True, max_length=16, null=True)),
                ('handover_certificate_police_number', models.CharField(blank=True, max_length=128, null=True)),
                ('handover_certificate_police_denotation', models.CharField(blank=True, max_length=4096, null=True)),
                ('comments', models.CharField(blank=True, max_length=1048576, null=True)),
                ('description', models.CharField(blank=True, max_length=1048576, null=True)),
                ('excluded', models.BooleanField(default=False)),
                ('state', models.CharField(max_length=30)),
                ('exhibit_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.exhibittype')),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.mandate')),
            ],
            options={
                'ordering': ['denotation'],
            },
            bases=(web.models.base.DefaultToStringMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExhibitComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denotation', models.CharField(max_length=1024)),
                ('description', models.CharField(blank=True, max_length=65536, null=True)),
                ('description_future', models.JSONField(blank=True, default=dict)),
                ('capacity', models.BigIntegerField(null=True)),
                ('serial_number', models.CharField(blank=True, max_length=128, null=True)),
                ('comments', models.CharField(blank=True, max_length=65536, null=True)),
                ('excluded', models.BooleanField(default=False)),
                ('additional_parts', models.CharField(blank=True, max_length=65536, null=True)),
                ('state', models.CharField(max_length=30)),
                ('component_typ', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.exhibitcomponenttype')),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.exhibit')),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.mandate')),
            ],
            options={
                'ordering': ['denotation'],
            },
            bases=(web.models.base.DefaultToStringMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExhibitDataImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
                ('denotation', models.CharField(max_length=64)),
                ('comments', models.CharField(blank=True, max_length=1048576, null=True)),
                ('description', models.CharField(blank=True, max_length=1048576, null=True)),
                ('md5_sum', models.CharField(max_length=4096, null=True)),
                ('size', models.BigIntegerField(null=True)),
                ('exhibit_component', models.ManyToManyField(blank=True, to='web.exhibitcomponent', verbose_name='backend_exhibitdataimage_exhibit_component_verbose_name')),
                ('image_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.exhibitdataimagetype')),
                ('main_exhibit_component', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mainexhibitdataimge_set', to='web.exhibitcomponent')),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.mandate')),
            ],
            options={
                'abstract': False,
            },
            bases=(web.models.base.DefaultToStringMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='exhibitcomponent',
            constraint=models.UniqueConstraint(fields=('denotation', 'mandate'), name='denotation_exhibit_component_unique_by_mandate'),
        ),
        migrations.AddConstraint(
            model_name='exhibit',
            constraint=models.UniqueConstraint(fields=('denotation', 'mandate'), name='denotation_exhibit_unique_by_mandate'),
        ),
    ]
