# Generated by Django 4.2.3 on 2023-08-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_exhibit_exhibitcomponent_exhibitdataimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='excluded',
        ),
    ]
