# Generated by Django 4.2.3 on 2023-08-06 14:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_exhibit_excluded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mobile', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='Mobile number must be 10 to 14 digits and can start with a plus sign.', regex='^(\\+?\\d{10,14})$')])),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/employees_profile_pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
