# Generated by Django 4.2.3 on 2023-08-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='can_access',
            field=models.ManyToManyField(blank=True, related_name='mandate_related_files', to='web.mandate'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
