# Generated by Django 4.2.3 on 2023-08-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_appuser_can_access_appuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='can_access',
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
