# Generated by Django 4.2.3 on 2023-08-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_contactperson_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_creation',
        ),
    ]
